---
driver:
  name: vagrant
  network:
    - ['forwarded_port', { guest: 80, host: 8880, auto_correct: false } ]

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[minimart-test]
