AllCops:
  Exclude:
    - 'Thorfile'

# Max line length
LineLength:
  Max: 160

# Allow 1.8 hash style
HashSyntax:
  Enabled: false

# Don't require a _ to split an integer like 1000.
Style/NumericLiterals:
  Enabled: false

# Allow either fail or raise.
Style/SignalException:
  Enabled: false

# Needed for metadata.rb
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# UTF8
Style/Encoding:
  Enabled: false
