settings:
  parallel: true

driver:
  name: docker
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash
  privileged: true

provisioner:
  name: chef_zero

platforms:
- name: centos-6.7
  driver:
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget
- name: centos-7.1
  driver:
    image: centos:centos7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    privileged: true
    provision_command:
      - /bin/yum install -y initscripts net-tools wget
- name: debian-7
  driver:
    platform: debian
    disable_upstart: false
    run_command: /sbin/init
  run_list:
    - recipe[apt]
    - recipe[netstat]
- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
  run_list:
    - recipe[apt]
    - recipe[netstat]
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
  run_list:
    - recipe[apt]
    - recipe[netstat]

suites:
  - name: default
    run_list:
      - recipe[mw_server_base]
      - recipe[mw_server_base::security]
    attributes: {
      authorization: {
        sudo: {
          users: ['kitchen'],
          sudoers_defaults: ['secure_path="/sbin:/bin:/usr/sbin:/usr/bin"']
        }
      },
      mw_server_base: {
        apt: {
          first_upgrade: false
        },
        authorization: {
          additional_superadmin_group: ['additional_admin']
        },
        postfix: {
          vault: {
            item: "google"
          }
        }
      }
    }
    data_bags_path: "test/integration/data_bags" 
