---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: debian-8.6
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.10
  - name: fedora-23
  - name: fedora-24

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
