---
driver:
  name: vagrant
driver_config:
 require_chef_omnibus: latest

provisioner:
  name: chef_zero
  environments_path: "test/environments"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: centos-6.7
  - name: centos-7.2
suites:
  - name: manager-development-master
    environments_path: "test/environments"
    data_bags_path: "test/data_bags"
    encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
    driver:
      network:
      - ["private_network", {ip: "172.16.10.10"}]
    run_list:
      - recipe[wazuh::testenvsetup]
      - recipe[wazuh::manager]
      - recipe[wazuh_filebeat::default]
    attributes:
    provisioner:
      client_rb:
        environment: development-master

  - name: manager-development-client
    environments_path: "test/environments"
    data_bags_path: "test/data_bags"
    encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
    driver:
      network:
      - ["private_network", {ip: "172.16.10.11"}]
    run_list:
      - recipe[wazuh::testenvsetup]
      - recipe[wazuh::manager]
      - recipe[wazuh_filebeat::default]
    attributes:
    provisioner:
      client_rb:
        environment: development-client

  - name: elastic-development
    environments_path: "test/environments"
    data_bags_path: "test/data_bags"
    encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
    driver:
      network:
      - ["private_network", {ip: "172.16.10.12"}]
      customize:
        memory: 2048
        cpus: 2
    run_list:
      - recipe[wazuh::testenvsetup]
      - recipe[wazuh_elastic::default]
    attributes:
    provisioner:
      client_rb:
        environment: development-master

  - name: agent-development
    driver:
      network:
      - ["private_network", { type: "dhcp" }]
    run_list:
      - recipe[wazuh::testenvsetup]
      - recipe[wazuh::agent]
    attributes:
         vagrant:
    provisioner:
      client_rb:
        environment: development
