name              'web_application'
version           '0.0.0'
description       'web_application'
maintainer        ''
maintainer_email  ''
license           'MIT License'
source_url        ''

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
