---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: mwrock/Windows2012R2
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[msys2::default]
    attributes:
      msys2:
        install_dir: 'C:/msys64'
        packages: ['git']
        override_package: true
        override_execute: true
