---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: appium_test
    run_list:
      - recipe[appium_test::android]
    attributes:
      java:
        jdk_version: 7
