---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: pester

platforms:
  - name: win-2012r2-standard-amd64-nocm
    transport:
      name: winrm
    driver_config:
      box:  opentable/win-2012r2-standard-amd64-nocm
      gui: true

suites:
  - name: default
    run_list:
      - recipe[webdeploymenttoolkit::default]
    attributes:
