default['ls_windows_ad']['domain_name'] = 'thewall.local'
default['ls_windows_ad']['safe_mode_admin_pswd'] = '!QAZSE$1qazse4'
default['ls_windows_ad']['admin_username'] = 'thewall.local\Administrator'
default['ls_windows_ad']['admin_pswd'] = '!QAZSE$1qazse4'
default['ls_windows_ad']['role'] = 'primary'
