---
<%
  db_host = ENV['KITCHEN_DB_HOST'] || '127.0.0.1'
  db_port = ENV['KITCHEN_DB_PORT'] || '3306'
  db_setup_auto = ENV['KITCHEN_DB_SETUP_AUTO'] || 'true'
  expose_port = ENV['KITCHEN_EXPOSE_PORT'] || 'false'
%>
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

verifier:
  name: inspec

provisioner:
  name: dokken
  attributes:
    icinga2:
      ignore_version: true
    icingaweb2:
      setup_config: false
      ignore_version: true
      <% if db_setup_auto == 'true' %>
      install_mysql_client: false
      <% else %>
      install_mysql_client: true
      <% end %>
      ido_db:
        db_host: <%= db_host %>
        db_port: <%= db_port %>
        db_password: X2BM0WKnN
        load_schema: true
      web2_db:
        db_host: <%= db_host %>
        db_port: <%= db_port %>
        db_password: X2BM0WKnN
        load_schema: true
      ini_config:
        resources:
          icingaweb2:
            host: <%= db_host %>
            password: X2BM0WKnN
          icinga2:
            host: <%= db_host %>
            password: X2BM0WKnN

    apt:
      confd:
        install_recommends: false

platforms:
  - name: ubuntu-14
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: ubuntu-16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian-8
    driver:
      image: debian:8.9
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: centos-6
    driver:
      image: centos:6.9
      pid_one_command: /sbin/init
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which curl

  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: fedora-26
    driver:
      image: fedora:26
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: amazon
    driver:
      image: amazonlinux:2017.03
      pid_one_command: /sbin/init
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

suites:
  - name: chef12package
    driver:
      chef_version: 12.21.4
      <% if expose_port == 'true' %>
      ports: '80'
      <% end %>
    verifier:
      inspec_tests:
        - test/smoke/default/package.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: package

  - name: chef13package
    driver:
      chef_version: 13.3.42
      <% if expose_port == 'true' %>
      ports: '80'
      <% end %>
    verifier:
      inspec_tests:
        - test/smoke/default/package.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: package

  - name: chef12source
    driver:
      chef_version: 12.21.4
      <% if expose_port == 'true' %>
      ports: '80'
      <% end %>
    verifier:
      inspec_tests:
        - test/smoke/default/source.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: source

  - name: chef13source
    driver:
      chef_version: 13.3.42
      <% if expose_port == 'true' %>
      ports: '80'
      <% end %>
    verifier:
      inspec_tests:
        - test/smoke/default/source.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: source

