dist: trusty
cache: bundler
sudo: required

language: ruby

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

rvm:
  - 2.4.3

services:
  - docker

before_install:
  - gem install bundler
  - gem update --system

bundler_args: --jobs 7 --retry 3

env:
  matrix:
    # - CHEF_VERSION=12.9.38
    # - CHEF_VERSION=12.22.1
    # - CHEF_VERSION=13.8.5
    - INSTANCE=system-install-debian-8
    - INSTANCE=system-install-debian-9
    - INSTANCE=system-install-centos-6
    - INSTANCE=system-install-centos-7
    - INSTANCE=system-install-fedora
    - INSTANCE=system-install-ubuntu-1604
    - INSTANCE=system-install-ubuntu-1804
    - INSTANCE=system-install-opensuse-leap
    - INSTANCE=system-install-oracle-linux
    - INSTANCE=system-install-amazon-linux
    - INSTANCE=user-install-debian-8
    - INSTANCE=user-install-debian-9
    - INSTANCE=user-install-centos-6
    - INSTANCE=user-install-centos-7
    - INSTANCE=user-install-fedora
    - INSTANCE=user-install-ubuntu-1604
    - INSTANCE=user-install-ubuntu-1804
    - INSTANCE=user-install-opensuse-leap
    - INSTANCE=user-install-oracle-linux
    - INSTANCE=user-install-amazon-linux

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1

notifications:
  email: false
  slack:
    rooms:
      -  mai-darwin:hxe0q88Tfq9MdGqceoCDrjcC#chef-pyenv
