---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.9
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
  - name: macosx-10.11
    driver:
      provider: vmware_fusion
  - name: macosx-10.12
    driver:
      provider: vmware_fusion

suites:
  - name: default
    run_list:
      - perforce
