---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
- name: centos-6.7
  driver_config:
    box: bento/centos-6.7

- name: centos-7.2
  driver_config:
    box: bento/centos-7.2

suites:
  - name: bridge
    run_list:
      - recipe[rundeck-bridge]
