---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.8
  - name: debian-6.0.10
  - name: centos-6.6
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[chef-dk-gem]
