name             'tmux-latest'
maintainer       'David Pell'
maintainer_email 'davidcpell@gmail.com'
license          'all_rights'
description      'Installs/Configures tmux'
long_description 'Installs/Configures the latest version of tmux from source'
source_url       'https://github.com/davidcpell/tmux-latest'
issues_url       'https://github.com/davidcpell/tmux-latest/issues'
supports         'ubuntu', '>= 14.04'
supports         'centos', '= 7.2'
version          '0.2.0'
