---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.8
    run_list:
      - recipe[yum]
  - name: centos-7.2
    run_list:
      - recipe[yum]
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2
      guest: windows
      communicator: winrm
      gui: false

suites:
  - name: default
    require_chef_omnibus: 12.14.60
    run_list:
      - recipe[metricbeat::default]
    attributes:
      metricbeat:
        config:
          metricbeat.modules:
          - module: system
            metricsets:
              - cpu
              - memory
              - network
              - process
            enabled: true
            period: 10s
            processes: ['.*']

          output.elasticsearch:
            hosts: ["127.0.0.1:9200"]

