---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: centos-6.8
  driver:
    image: centos:6.8
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts systemd-sysv which lsof

- name: amazonlinux
  driver:
    image: amazonlinux:2017.03
    platform: amazon
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which
    pid_one_command: /sbin/init

suites:
  - name: default12
    driver:
      chef_version: 12.21.3
    run_list:
      - recipe[auditbeat::default]
    attributes:
      auditbeat:
        config:
          "output.elasticsearch":
              hosts: ["127.0.0.1:9200"]

  - name: default13
    driver:
      chef_version: 13.2.20
    run_list:
      - recipe[auditbeat::default]
    attributes:
      auditbeat:
        config:
          "output.elasticsearch":
              hosts: ["127.0.0.1:9200"]
