---
driver:
  name: azurerm

driver_config:
  subscription_id: "<%= ENV['CHEF_AZURE_SUBSCRIPTION_ID']%>"
  location: East US
  machine_size: Standard_A1

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: linux-ubuntu-14.04
    driver_config:
      image_urn: Canonical:UbuntuServer:14.04.5-LTS:latest
      vm_name: ubuntu14-vm
      vm_tags:
        ostype: linux
        distro: ubuntu
      azure_resource_group_prefix: kitchenub14
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-ubuntu-16.04
    driver_config:
      image_urn: Canonical:UbuntuServer:16.04.0-LTS:latest
      vm_name: ubuntu16-vm
      vm_tags:
        ostype: linux
        distro: ubuntu
      azure_resource_group_prefix: kitchenub16
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-debian-7
    driver_config:
      image_urn: credativ:Debian:7:latest
      vm_name: debian7-vm
      vm_tags:
        ostype: linux
        distro: debian
      azure_resource_group_prefix: kitchendeb7
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-debian-8
    driver_config:
      image_urn: credativ:Debian:8:latest
      vm_name: debian8-vm
      vm_tags:
        ostype: linux
        distro: debian
      azure_resource_group_prefix: kitchendeb8
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-suse-11-SP4
    driver_config:
      image_urn: SUSE:SLES:11-SP4:latest
      vm_name: suse11-vm
      vm_tags:
        ostype: linux
        distro: suse
      azure_resource_group_prefix: kitchensuse11
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-suse-12-SP3
    driver_config:
      image_urn: SUSE:SLES:12-SP3:latest
      vm_name: suse12-vm
      vm_tags:
        ostype: linux
        distro: suse
      azure_resource_group_prefix: kitchensuse12
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-RHEL-6.9
    driver_config:
      image_urn: RedHat:RHEL:6.9:latest
      vm_name: rhel6-vm
      vm_tags:
        ostype: linux
        distro: rhel
      azure_resource_group_prefix: kitchenrhel6
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-RHEL-7.2
    driver_config:
      image_urn: RedHat:RHEL:7.2:latest
      vm_name: rhel7-vm
      vm_tags:
        ostype: linux
        distro: rhel
      azure_resource_group_prefix: kitchenrhel7
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-Oracle-6.9
    driver_config:
      image_urn: Oracle:Oracle-Linux:6.9:latest
      vm_name: oraclelin69-vm
      vm_tags:
        ostype: linux
        distro: oracle
      azure_resource_group_prefix: kitchenoraclelinux69
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
  - name: linux-Oracle-7.4
    driver_config:
      image_urn: Oracle:Oracle-Linux:7.4:latest
      vm_name: oraclelin74-vm
      vm_tags:
        ostype: linux
        distro: oracle
      azure_resource_group_prefix: kitchenoraclelinux74
    transport:
      name: ssh
      ssh_key: "<%= ENV['CHEF_AZURE_VM_SSH_KEY']%>"
#- name: windows-server-2008-R2
#  driver_config:
#    image_urn: MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest
#    vm_name: win2008r2-vm
#    vm_tags:
#      ostype: windows
#      distro: win2008R2
#    azure_resource_group_prefix: kitchenwin2008
#  transport:
#    name: winrm
#    username: "<%= ENV['CHEF_WINRM_USERNAME']%>"
#    password: "<%= ENV['CHEF_WINRM_PASSWORD']%>"
  - name: windows-server-2012-R2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
      vm_name: win2012r2-vm
      vm_tags:
        ostype: windows
        distro: win2012R2
      azure_resource_group_prefix: kitchenwin2012
    transport:
      name: winrm
      username: "<%= ENV['CHEF_WINRM_USERNAME']%>"
      password: "<%= ENV['CHEF_WINRM_PASSWORD']%>"
  - name: windows-server-2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
      vm_name: win2016
      vm_tags:
        ostype: windows
        distro: win2016
      azure_resource_group_prefix: kitchenwin2016
    transport:
      name: winrm
      username: "<%= ENV['CHEF_WINRM_USERNAME']%>"
      password: "<%= ENV['CHEF_WINRM_PASSWORD']%>"


suites:
  - name: default
    run_list:
      - recipe[deep-security-agent::default]
      - recipe[deep-security-agent-test::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      deep_security_agent:
        dsm_agent_download_hostname: "<%= ENV['CHEF_DSA_DOWNLOAD_HOSTNAME']%>"
        dsm_agent_download_port: "<%= ENV['CHEF_DSA_DOWNLOAD_PORT']%>"
        dsm_agent_activation_hostname: "<%= ENV['CHEF_DSA_ACTIVATION_HOSTNAME']%>"
        dsm_agent_activation_port: "<%= ENV['CHEF_DSA_ACTIVATION_PORT']%>"
        tenant_id: "<%= ENV['CHEF_DSA_TENANT_ID']%>"
        token: "<%= ENV['CHEF_DSA_TOKEN']%>"