language: ruby
bundler_args: --without integration development
rvm:
  - 2.2.2
branches:
  only:
    - master
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script:
  - bundle exec rake lint
