---
driver:
  name: vagrant
  customize:
    memory: 8096
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:

provisioner:
  name: chef_solo
#  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-15.04
#  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[flink::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      #- recipe[flink::jobmanager]
      #- recipe[flink::taskmanager]
      - recipe[flink::yarn]
      #- recipe[flink::wordcount]
    attributes:
         java:
            jdk_version: 8
         vagrant: "true"
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
         hops:
            nn:
               private_ips: ["10.0.2.15"]
               direct_memory_size: 300
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "true"
         apache_hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
         flink:
            hadoop_distribution: "hops"
            jobmanager:
               private_ips: ["10.0.2.15"]
            taskmanager:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: "false"
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
