---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4445}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 4446}]
    attributes:
      selenium_grid:
        username: vagrant
        password: vagrant
      windows_screenresolution:
        rdp_password: "!mzKf!WF&q[c@&!T" # meet the password policy requirements

suites:
  - name: default
    run_list:
      - recipe[java_se]
      - recipe[selenium_grid_test::package]
      - recipe[selenium_grid::hub]
      - recipe[selenium_grid::node]
    attributes:
      selenium_grid:
        display:
          width: 1280
          height: 1024
        chrome:
          max_instances: 5
        firefox:
          max_instances: 5
        htmlunit:
          max_instances: 1
        ie:
          max_instances: 1
