language: ruby
cache: bundler
rvm:
- 2.3.2
deploy:
  skip_cleanup: true
  edge: true
  edge:
    source: criteo-forks/dpl
    branch: chef_ruby2
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Operating Systems & Virtualization
  client_key: ".travis/client.pem"
  on:
    tags: true
env:
  global:
  - secure: kFWwXHtEm7dtvtF5wFW8J/4ATTw5MBVcLAWfndsAqO7FUIegulN3XuZHaf8uRF686wmAZs2nWHUDr6SWmsZ68+A/nSZtFS4vGHIDoaHdOfq08JLDB1G/ffvjMguU1V/Teavguq/klQ9Y0slnQ64+ESwHhgBVmdOiupdb9x1IpnxRGoPEZ93Mz5L+Lf6+W6oSDECWVtEAgt/juwuAYg+pKf3HQ7K7V0u2mUsyL6vBa875ewqkRgaV23uS+zeAQXYwlu6wjxSwSlQyi8i80u5eo2KqPh9ea0wSbp04o9wyAo+eF2Vonc9JdcuTd2yrTRnVI9F2bDaDpFmF6972VnMq62GUfvZz13QoB1P0URcYeHiSM8tvIrl+UOFVfd4c9fShqe/mOcmiGGtrh/udtO0ngbAbIAtNkf7/wnqS0H5n9UoZhY7g+ge7SUWXMdPNzKuNUiKyQovmpBeAqVzmrQiAVhW5i4r11bdnl3DRIJtAmorp9g/WiSG7wOMN9O449nQDmm+GD260i6nK4+m0nKiNSFx4D53dQEdxDZvZQSGgxQ0E79zrr30esguIVQQJXlCz5XKSlHYXSB7XXiSNxCv2po3rnRDcgMQpnbWLhQk1O6IRQtVnX3HPgDccdxADTwznRfspFWZgeJM+TMC737rqIMKctu/bJYmZKIXmCy8836s=
  - secure: mB6qWYEQmYKrkaaPNLNzTCbd9KUiKS2sO55BYFGApBn62ZctmlVXxWyVt+FSkrl6lbXetRPCmL3F9iiqwZtoqszD6ygvCMcCNF83VhS/BRzRFRTnY+jpdHE1brCAB8iAPRyKezIHCSrYBO0uXsr20m0vdnPQTnl6HxiUrBpfLWZEcTA0THDQVI50wugXYDIWT9togLEDH3YXd6ZootSR+OvSol6CAIsS3WSVPR7R98Xid0G9ahomC8mGF6ShpAv9hRwyjs88QOkqNdPKi+U9HJHR086vZ6NTHeLmaCVaN+rN6PtFIkM1XvCUNjLWkl17DKr4R2IYnzHuVtmQ6bLgHlVlUOdQ4o5p6NfnL08cFKDHn4nPNplB8M7QQ4gnRxFUO6+HpzrrRIJLIrRv8uc9T+Xn0XL4rZqkoXnZaowWV+/8/xMNNVHKoXfi5TCjAfdoFnKJvTZ+gaVxXWCSKLh7fnGsSpGS8b+yUh86ihqip++jr9MivBc/4wcIPZVNXfw+soISAWIkZq0yRtTvFjpNW9ygwwRXbtGthp9aq5mtF9zLf/5lRGbIfVD8dD89gck2dgiYfPKhj2+3iChDS7zwa6SI6PZ/iP4bUlsmUAYgHcY9Q0XxU34ksZi7ylFMTDEwXwfcXFZSOp4v9Gh4F5bEoapTnyBX/qmu76jxyFzw/II=
  - secure: Ky+bt4OObK+/1EaOPLf7ryYY0EnlWE7C1LTDpEnmTNmUhgHJ5D3jjb+5EljVvWZ1BS5pTO/VPiCxCQxKRV31AjMsbAwJEdkMlOGepZtmspOGwMZczSYEUle4E0SYZFdmHM7CzSyXGJ+j3wHSrGKGi82quo3i+UKa478VpK6x89A+1d+nKglTQHILtUrOQjsgJUci+Uu3lsrygiKWuLcITRWGbJKZRV0d0GKX7jz3ChNBzai1kHLGMuVj5gDz4yAIqa9Nv4BPLts1z0ylXoVP8st9FN5do5iVmT0UYNfV29HreHfuomK02rACrSZyHtilROwirhhula/eUsK6SIgse0zhIzFd3/X6dE39ecJmHTqu0x1GrE0yh6TC/NMDcTQzsrAzCWf/HlHB0xUNKsX6a5ei5B6CS1sDTGAa6Hnv4YMXGVh/DS+lWCkVfvSXGM+Re5UO7/xUjethTYmE36kBS7UStreoEEsTKlasU1rasUEFqArepQumTwKvwTPUzcEWFAauX6xyjcFs0XlmVHmCciyp7Qb4RcTb6vEMR/S7Ovf0DnZZbXvg8YHp93+h9s/K7Ulkspk5wDbvej1/6+rbv0bEmYS/oKKFyKvcupG3XsTm2t+nMfLlw5A0vPtY2Iyq77kXLxTNqsui2PAo2hm6qisq5Ehwbuzci8DmJj2FyJU=
  - secure: aBkM+OYeTisCse3MkSTvC2cwcvz+u1mShZ8u51DRxDCSne6hTZMfMuMBejnqDRW5YLu87w4eCOoDuNOuLEnEaJuJEY76Xty74U4wxNZsNAPIrG+sg0ohAoSNgKCsd3qR6pV1Ng8CBqiovEUvqmATcR0o7UNwY2v1FwyjFBkiwfbjzXSSYjkSjF/I0svk7yG6imYwxlm5GWq4ova46HxHylk26s4FkzmdquV1IZnoqo6Fp6KxH8PVXR8Zmk8PzG7gXK/NxdBlCFyCTK1y469iKAqlWGaJ4hjQTNekdMH9xwSglFAQ3r0YV+WbqxcPmVnMlTcd2xqjTPDKDfNlK5D+py0wf/KhqbZtHOZWNEgi8gqTpNRDhOUci0rEdoqUGxeo4j3ica1o9fPrmK9eZo2z4nQj/neCJnul5KfCn+SrNcWR4QBB+0iXwvoGl9sFl5HSEDa2P/pkhI51YA26Z2QY41VnaOP9RNRNY6cu4FlTIP/7Act75dihRG/q1lNy2ZTbb61mE1m7FDs+mBzvIefkdjiKr7D04dPA3QrTMMmumGUxnfPl5D56m363LcrEz2XWKyOatk5BRveCEpIF1CU1qAMgO0rYi2LKXK515Zv7+bfx1Gqly74gksmBt6w+6btea7zGcv9Zasu6wbJU6vvhRkULxSmOTsH56wIvFhoBAIs=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9e3ec1330859_key -iv $encrypted_9e3ec1330859_iv
      -in .travis/client.pem.enc -out .travis/client.pem -d
before_install:
  - openssl aes-256-cbc -K $encrypted_9e3ec1330859_key -iv $encrypted_9e3ec1330859_iv
      -in .travis/travis-ci.pem.enc -out ~/.ssh/id_rsa -d
