---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
  - name: debian-6.0.10
    run_list:
    - apt::default
  - name: ubuntu-12.04
    run_list:
    - apt::default
  - name: ubuntu-14.04
    run_list:
    - apt::default

suites:
  - name: default
    run_list:
    - recipe[krb5_utils::default]
    attributes:
      krb5:
        default_realm: 'KRB5.LOCAL'
        default_realm_kdcs: [ 'localhost' ]
        default_realm_admin_server: 'localhost'
      krb5_utils:
        krb5_service_keytabs:
          hdfs:
            owner: 'hdfs'
            group: 'hadoop'
            mode: '0640'
          HTTP:
            owner: 'hdfs'
            group: 'hadoop'
            mode: '0640'
        krb5_user_keytabs:
          yarn:
            owner: 'yarn'
            group: 'hadoop' 
            mode: '0640'
