---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: ubuntu-1604
    driver_plugin: docker
    driver:
      image: ernestasposkus/ubuntu1604
      run_command: '/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: centos-6
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos6
      run_command: '/sbin/init'
      run_options: ''
  - name: ubuntu-1404
    driver_plugin: docker
    driver:
      image: ernestasposkus/ubuntu1404

suites:
  - name: default
    run_list:
      - recipe[test-clickhouse::setup]
      - recipe[test-clickhouse::test_clickhouse_server]
      - recipe[test-clickhouse::test_zookeeper_config]
      - recipe[test-clickhouse::test_macros_config]
      - recipe[test-clickhouse::test_remote_servers_config]
      - recipe[test-clickhouse::test_custom_config]
