driver:
  name: vagrant
  require_chef_omnibus: '13.0.113'

provisioner:
  name: chef_zero
  max_retries: 1
  wait_for_retry: 1
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
  - name: windows-2008r2
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
suites:
  - name: default
    run_list:
      - recipe[schannel::default]