#
# Copyright (c) 2016 Sam4Mobile, 2017 Make.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
#   <% grep = "grep '^nameserver' /etc/resolv.conf | grep -v 127.0.0.1" %>
#   <% fallback = `#{grep} | cut -d" " -f2`.lines.map(&:chomp).first %>

driver:
  name: docker_cli
  volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  command: /usr/lib/systemd/systemd
  security_opt: seccomp=unconfined
  skip_preparation: true
  require_chef_omnibus: false
  instance_host_name: true
  instance_container_name: true
  build_pull: true

transport:
  name: docker_cli

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: centos-7
    driver_config:
      image: sbernard/centos-systemd-kitchen

suites:
  - name: nxredirect-cookbook-normal
    run_list:
      - recipe[nxredirect-cookbook]
      - recipe[bind-ddns::server]
    attributes:
      nxredirect-cookbook:
        config:
          fallback: "<%= fallback.empty? ? '8.8.8.8' : fallback %>:53"
        package_retries: 1
      bind-ddns:
        set_resolv_conf: true
        server: 127.0.0.1
        options:
          listen-on: "port 53053 { 127.0.0.1; }"
          listen-on-v6: "port 53053 { ::1; }"
        zones:
          - name: org
            config:
              type: master
              file: dynamic/db-org
              allow-update: "{ key org; }"
            ns: [ ns.org. ]
            a:
              ns.org.: eth0
              isc.org.: eth0 # override isc.org
        records:
          - zone: org
            domain: me.org
            data: eth0
        keys:
          - name: org
            secret: 9ZDQZxLEBuho4+O0EuGOYA==
        package_retries: 1
  - name: nxredirect-cookbook-noop
    run_list:
      - recipe[nxredirect-cookbook]
    attributes:
      nxredirect-cookbook:
        servers: [ 'notme' ]
  - name: nxredirect-cookbook-withservers
    run_list:
      - recipe[nxredirect-cookbook]
    attributes:
      nxredirect-cookbook:
        erlang_version: '19.3-1.el7.centos'
        package_retries: 1
        servers: [ 'nxredirect-cookbook-withservers-centos-7' ]
