language: ruby

cache:
  - bundler
  - apt

env: 
  - BERKSHELF_PATH=/tmp/

before_install:
  - sudo apt-get update -qq
  - curl -L https://www.chef.io/chef/install.sh | sudo bash

install:
  - bundle install  
  - bundle exec berks vendor /tmp/cookbooks
  - cp dummy-validation.pem /tmp/validation.pem
  - cp dna.json /tmp/dna.json

script:
  - chef-client -z -c client.rb -j dna.json
