---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.1

suites:
  - name: binary_install
    run_list:
      - recipe[sbp_packer_test]
      - recipe[sbp_packer::default]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default

  - name: source_install
    run_list:
      - recipe[sbp_packer_test]
      - recipe[sbp_packer::default]
    attributes:
      packer:
        install_method: 'source'
    verifier:
      inspec_tests:
        - test/smoke/default
