name             'systemd_networkd'
maintainer       'Intel Corp'
maintainer_email 'david.m.oneill@intel.com'
license          'Apache v2.0'
description      'Configures systemd_networkd'
source_url       'https://github.com/Intel-Corp/systemd_networkd'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.0'
supports         'ubuntu'
supports         'redhat'
supports         'fedora'
supports         'centos'
supports         'debian'
supports         'gentoo'
