---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2
  - name: centos-6.3

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[docker-machine::default]
    attributes:
