name             'pathogen'
maintainer       'David Pell'
maintainer_email 'davidcpell@gmail.com'
license          'all_rights'
description      'Installs/Configures pathogen vim plugin manager'
long_description 'Installs/Configures pathogen vim plugin manager'
source_url       'https://github.com/davidcpell/pathogen'
issues_url       'https://github.com/davidcpell/pathogen/issues'
supports         'ubuntu', '>= 14.04'
supports         'centos', '= 7.2'
version          '0.4.4'
