driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: windows-8.1
    driver_config:
      box: chef/windows-8.1-enterprise
  - name: windows-10
    driver_config:
      box: chef/windows-10-enterprise
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: windows-2016
    driver_config:
      box: chef/windows-server-2016-standard
suites:
  - name: default
    run_list:
      - recipe[test::default]
