name             'chocolatey_config'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Provides a chocolatey_config resource for managing Chocolatey sources.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
supports         'windows'
source_url       'https://github.com/chef-cookbooks/chocolatey_config'
issues_url       'https://github.com/chef-cookbooks/chocolatey_config/issues'
chef_version     '>= 13.0'
