---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.7
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[patchman::default]
