---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: smoke-default
    run_list:
      - recipe[kubernetes-stack-test::default]
    verifier:
      inspec_tests:
        - test/smoke/default

  - name: smoke-kubectl-default
    run_list:
      - recipe[kubernetes-stack-test::kubectl_install_default]
      - recipe[kubernetes-stack-test::kubectl_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_default_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-kubectl
    run_list:
      - recipe[kubernetes-stack-test::kubectl_install_default]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-kubectl-specific-version
    run_list:
      - recipe[kubernetes-stack-test::kubectl_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_specific_version_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-kubectl-uninstall
    run_list:
      - recipe[kubernetes-stack-test::kubectl_uninstall]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_uninstall_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-helm-default
    run_list:
      - recipe[kubernetes-stack-test::helm_install_default]
      - recipe[kubernetes-stack-test::helm_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/helm/helm_default_test.rb
    attributes:
      kubernetes-stack:
        helm:
          enabled: true

  - name: smoke-helm
    run_list:
      - recipe[kubernetes-stack-test::helm_install_default]
    verifier:
      inspec_tests:
        - test/smoke/helm/helm_test.rb
    attributes:
      kubernetes-stack:
        helm:
          enabled: true

  - name: smoke-helm-specific-version
    run_list:
      - recipe[kubernetes-stack-test::helm_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/helm/helm_specific_version_test.rb
    attributes:
      kubernetes-stack:
        helm:
          enabled: true

  - name: smoke-helm-uninstall
    run_list:
      - recipe[kubernetes-stack-test::helm_uninstall]
    verifier:
      inspec_tests:
        - test/smoke/helm/helm_uninstall_test.rb
    attributes:
      kubernetes-stack:
        helm:
          enabled: true

  - name: smoke-gcloud-default
    run_list:
      - recipe[kubernetes-stack-test::gcloud_install_default]
      - recipe[kubernetes-stack-test::gcloud_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/gcloud/gcloud_default_test.rb
    attributes:
      kubernetes-stack:
        gcloud:
          enabled: true

  - name: smoke-gcloud
    run_list:
      - recipe[kubernetes-stack-test::gcloud_install_default]
    verifier:
      inspec_tests:
        - test/smoke/gcloud/gcloud_test.rb
    attributes:
      kubernetes-stack:
        gcloud:
          enabled: true

  - name: smoke-gcloud-specific-version
    run_list:
      - recipe[kubernetes-stack-test::gcloud_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/gcloud/gcloud_specific_version_test.rb
    attributes:
      kubernetes-stack:
        gcloud:
          enabled: true

  - name: smoke-gcloud-uninstall
    run_list:
      - recipe[kubernetes-stack-test::gcloud_uninstall]
    verifier:
      inspec_tests:
        - test/smoke/gcloud/gcloud_uninstall_test.rb
    attributes:
      kubernetes-stack:
        gcloud:
          enabled: true
