---
driver:
  name: vagrant
  vm_hostname: 'postfixadmin.local'
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  data_path: test/shared
  # client_rb:
  #   treat_deprecation_warnings_as_errors: true # WiP on some depends

platforms:
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]
- name: debian-7.8
  run_list: recipe[apt]
- name: debian-8.7
  run_list: recipe[apt]
- name: centos-5.11
  run_list: recipe[selinux::disabled]
- name: centos-6.6
  run_list: recipe[selinux::disabled]
- name: fedora-20
  run_list: recipe[selinux::disabled]

suites:
- name: mysql
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  excludes:
  # mysql cookbook: No candidate version available for mysql-community-server
  - centos-7
  # Can't connect to MySQL server on '127.0.0.1' (111)
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  # mysql cookbook: undefined method `split' for nil:NilClass
  - ubuntu-16.10
- name: postgresql
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      database:
        type: postgresql
  excludes:
  # cpio: cap_set_file failed - Operation not supported
  - centos-7
  # /etc/init.d/postgresql: line 24: /etc/sysconfig/network: No such file or directory
  - scientific-6.6
  # apache2 cookbook: No candidate version available for libapache2-mod-php5
  - ubuntu-16.04
  # php cookbook: No candidate version available for php5-cgi
  - ubuntu-16.10
- name: nginx
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: nginx
  excludes:
  # mysql cookbook: mysql-*.remi.x86_64 conflicts with file from package mysql-*.i386
  - centos-5
  # mysql cookbook: No candidate version available for mysql-community-server
  - centos-7
  # /etc/init.d/nginx: line 17: /etc/sysconfig/network: No such file or directory
  - scientific-6.6
  # Can't connect to MySQL server on '127.0.0.1' (111)
  - ubuntu-12.04
  - ubuntu-14.04
  # php-fpm cookbook: No candidate version available for php5-fpm
  - ubuntu-16.04
  # mysql cookbook: undefined method `split' for nil:NilClass
  - ubuntu-16.10
- name: without-webserver
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: false
- name: map_files
  run_list:
  - recipe[netstat]
  - recipe[postfix-full]
  - recipe[postfixadmin_test::map_files]
  excludes:
  - centos-7
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  - ubuntu-16.10
- name: ssl
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      ssl: true
  excludes:
  - centos-7
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  - ubuntu-16.10
- name: ssl-port
  run_list:
  - recipe[netstat]
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      port: 8443
      ssl: true
  excludes:
  - centos-7
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  - ubuntu-16.10
