rvm:
- 2.2
- 2.3

sudo: required

services: docker

env:
  matrix:
  - TESTS="style unit" CHEF_VERSION="~> 12.0"
  - TESTS="integration[mysql-centos-5,verify]"
  - TESTS="integration[mysql-centos-6,verify]"
  - TESTS="integration[mysql-debian-7,verify]"
  - TESTS="integration[mysql-debian-8,verify]"
  - TESTS="integration[mysql-scientific-66,verify]"
  - TESTS="integration[postgresql-centos-5,verify]"
  - TESTS="integration[postgresql-centos-6,verify]"
  - TESTS="integration[postgresql-debian-7,verify]"
  - TESTS="integration[postgresql-debian-8,verify]"
  - TESTS="integration[postgresql-ubuntu-1204,verify]"
  - TESTS="integration[postgresql-ubuntu-1404,verify]"
  - TESTS="integration[nginx-centos-6,verify]"
  - TESTS="integration[nginx-debian-7,verify]"
  - TESTS="integration[nginx-debian-8,verify]"
  - TESTS="integration[without-webserver-centos-6,verify]"
  - TESTS="integration[map-files-centos-6,verify]"
  - TESTS="integration[ssl-centos-6,verify]"
  - TESTS="integration[ssl-port-centos-6,verify]"

matrix:
  exclude:
  - rvm: 2.2
    env: TESTS="integration[mysql-centos-5,verify]"
  - rvm: 2.2
    env: TESTS="integration[mysql-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[mysql-debian-7,verify]"
  - rvm: 2.2
    env: TESTS="integration[mysql-debian-8,verify]"
  - rvm: 2.2
    env: TESTS="integration[mysql-scientific-66,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-centos-5,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-debian-7,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-debian-8,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-ubuntu-1204,verify]"
  - rvm: 2.2
    env: TESTS="integration[postgresql-ubuntu-1404,verify]"
  - rvm: 2.2
    env: TESTS="integration[nginx-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[nginx-debian-7,verify]"
  - rvm: 2.2
    env: TESTS="integration[nginx-debian-8,verify]"
  - rvm: 2.2
    env: TESTS="integration[without-webserver-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[map-files-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[ssl-centos-6,verify]"
  - rvm: 2.2
    env: TESTS="integration[ssl-port-centos-6,verify]"

before_install:
- chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.2.22
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
- chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- chef --version
- cookstyle --version
- foodcritic --version

script: travis_retry chef exec bundle exec rake $TESTS
