<% require 'kitchen-sync' %>
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41

platforms:
- name: centos-7.1
  driver_plugin: ec2
  driver_config:
    username: <%= ENV['AWS_CLOUD_USER'] %>
    image_id: <%= ENV['AWS_CLOUD_AMI'] %>
    flavor_id: <%= ENV['AWS_INSTANCE_TYPE'] %>

suites:
- name: default
  run_list:
    - recipe[taurus::default]
- name: jmeter_service
  run_list:
  - recipe[taurus::default]
  attributes:
    taurus:
      firewall_support: true
      jmeter_service: true
      locustio_service: false
      jmeter_support: true
      locustio_support: false
      ab_support: false
      siege_support: false
      gatling_support: false
      tsung_support: false
- name: locustio_service
  run_list:
  - recipe[taurus::default]
  attributes:
    taurus:
      firewall_support: true
      jmeter_service: false
      locustio_service: true
      jmeter_support: false
      locustio_support: true
      ab_support: false
      siege_support: false
      gatling_support: false
      tsung_support: false
