---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - role[debian_platform_family]
  - name: ubuntu-14.04
    run_list:
      - role[debian_platform_family]
  - name: debian-7.9
    run_list:
      - role[debian_platform_family]
  - name: debian-8.2
    run_list:
      - role[debian_platform_family]
  - name: centos-6.7
    run_list:
      - role[rhel_platform_family]
  - name: centos-7.1
    run_list:
      - role[rhel_platform_family]

suites:
  - name: default
    run_list:
      - role[test]
