name              'br-ruby'
version           '0.5.2'
description       'Installs Ruby versions'
maintainer        'Jim Pruetting'
maintainer_email  'core-team@builtbyrobots.com'
license           'MIT License'
source_url        'https://github.com/built-by-robots/ruby-cookbook'

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
