---
<%
  chef_omnibus_url = ENV['KITCHEN_CHEF_OMNIBUS_URL'] || nil
%>
driver:
  name: vagrant

provisioner:
  name: chef_zero
  <% if chef_omnibus_url %>
  chef_omnibus_url: '<%= chef_omnibus_url %>'
  <% end %>

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5

suites:
  - name: version1
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 1.7.3

  - name: version2
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 2.4.3

  - name: version5
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config_v5:
          cluster.name: "foo"
        plugins:
          x-pack:
            install_source: x-pack -b
        version: 5.1.2
