---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  require_chef_omnibus: 12.18.31

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      require_chef_omnibus: 12.18.31


suites:
  - name: default
    run_list:
      - recipe[alfresco-db::default]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    attributes:
