Metrics/BlockLength:
  Enabled: false
Style/AndOr:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
UnusedBlockArgument:
  Enabled: false
LineLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
