---
driver_plugin: vagrant
driver_config:
  customize:
    # Zenoss doesn't do well with the default 256MB
    # Avoid OSError: [Errno 12] Cannot allocate memory when starting Zenoss
    # TODO - Core 3 has far less requirements. Figure out if its possible
    # to only have the really high memory amount on Core4 suite instances
    memory: 3072
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: zenoss_core3
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss::server]
  attributes:
    zenoss:
      server:
        version: "3.2.1-0"
    java:
      oracle:
        accept_oracle_download_terms: true
- name: zenoss_core4
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss::server]
  attributes:
    zenoss:
      server:
        version: "4.2.4"
    java:
      oracle:
        accept_oracle_download_terms: true
    minitest:
      filter: /zenoss/
