build:
  image: rakuten/chefdk
  commands:
    - mkdir -p ${HOME}/.berkshelf
    - echo "{\"ssl\":{\"verify\":false}}" > ${HOME}/.berkshelf/config.json
    - mkdir -p ${PWD}/.chef
    - echo $CHEF_KEY | base64 --decode > ${PWD}/.chef/client.pem
    - chmod 400 ${PWD}/.chef/client.pem
    - echo "node_name 'drone-test'" > ${PWD}/.chef/knife.rb
    - echo "client_key '${PWD}/.chef/client.pem'" >> ${PWD}/.chef/knife.rb
    - echo 'ssl_verify_mode :verify_none' >> ${PWD}/.chef/knife.rb
    - berks install
    - chef exec rubocop
    - chef exec foodcritic -f any .
environment:
  - CHEF_KEY="$$chef_client_key"
notify:
  slack:
    webhook_url: $$slack_url
    channel: automation-dev
    username: drone

