AllCops:
  Exclude:
    - Vagrantfile
    - Thorfile

Documentation:
  Enabled: false
NumericLiterals:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
CommentAnnotation:
  Enabled: false
StringLiterals:
  Enabled: false
LineLength:
  Enabled: false
HashSyntax:
  Enabled: false
