---
driver:
  name: vagrant
  network:
    - - forwarded_port
      - guest: 135
        host: 135
        auto_correct: true
    - - forwarded_port
      - guest: 3389
        host: 3389
        auto_correct: true
    - - forwarded_port
      - guest: 5985
        host: 5985
        auto_correct: true
  forward_agent: yes
  communicator: winrm
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero_scheduled_task
  require_chef_omnibus: 12.8.1

verifier:
  name: pester

platforms:
  - name: windows-2012R2
    driver:
      vm_hostname: true
      box: enarciso/windows-2012R2

suites:
  - name: default
    run_list:
      - recipe[dsc-test::default]
    attributes:
