---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_file: "/tmp/kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default12
    driver:
      require_chef_omnibus: 12.21.3
    run_list:
      - recipe[chronograf::default]

  - name: default13
    driver:
      require_chef_omnibus: 13.2.20
    run_list:
      - recipe[chronograf::default]
