---
driver:
  name: vagrant
  customize:
    memory: 5000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
#  - ["forwarded_port", {guest: 50070, host: 57777}]
#  - ["forwarded_port", {guest: 50075, host: 57775}]
#  - ["private_network", ip: "192.168.0.2"]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-15.04
#  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[apache_hadoop::install]
      - recipe[apache_hadoop::nn]
      - recipe[apache_hadoop::dn]
      - recipe[apache_hadoop::rm]
      - recipe[apache_hadoop::nm]
      - recipe[apache_hadoop::jhs]
#      - recipe[apache_hadoop::ps]
#      - recipe[apache_hadoop::jn]

    attributes:
         apache_hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            ps:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            jn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            native_libraries: "false"
         kzookeeper:
            default:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "false"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"

