---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  require_chef_omnibus: 12.18.31

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: utils
    verifier:
      inspec_tests:
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
    run_list:
      - recipe[alfresco-utils::java]
      - recipe[alfresco-utils::package-repositories]
      - recipe[alfresco-utils::node_json]
    attributes:
