---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "data_bags"
    encrypted_data_bag_secret_key_path: "vagrant_encrypted_data_bag_secret"
    attributes: 
      dirsrv:
        use_yum_epel: true
    run_list:
      - recipe[dirsrv::_test_kitchen]
