---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: testing
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: package-master
    driver:
      tags:
        Name: et-mesos-package-master
    run_list:
      - recipe[zookeeper_minimal]
      - recipe[et_mesos::master]
    attributes:
      et_mesos:
        zk: 'zk://localhost:2181/mesos'
        package:
          with_zookeeper: true
        master:
          quorum: 1
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6

  - name: package-slave
    driver:
      tags:
        Name: et-mesos-package-slave
    run_list:
      - recipe[zookeeper_minimal]
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[et_mesos::master]
      - recipe[et_mesos::slave]
    attributes:
      et_mesos:
        zk: 'zk://localhost:2181/mesos'
        slave:
          attributes:
            rackid: us-east-1b
        master:
          quorum: 1
        # these keys below are only for master configurations.
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6
        package:
          with_zookeeper: false
