---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: ../../data_bags

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[rancher-ha::default]
      - recipe[rancher-ha::db]
      - recipe[rancher-ha::server]
      - recipe[rancher-ha::nginx]
    attributes:
