---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 13.6.4

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[tester::default]
      - recipe[chef_ca::default]
    verifier:
      inspec_tests:
        - test/default/inspec
    attributes:
