---
driver:
  name: vagrant
  require_chef_omnibus: 12.18.31

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: package
    run_list:
      - recipe[omni_ruby::default]
    attributes:
      omni_ruby:
        method: package

  - name: source
    run_list:
      - recipe[omni_ruby::default]
    attributes:
      omni_ruby:
        method: source

  - name: ree
    run_list:
      - recipe[omni_ruby::default]
    attributes:
      omni_ruby:
        method: ree
