name             'omni_ruby'
maintainer       'Erik Kranzusch'
maintainer_email 'erikk@spindance.com'
license          'Apache-2.0'
description      'Installs ruby'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.1'
issues_url       'https://github.com/spindance-ops/omni_ruby/issues'
source_url       'https://github.com/spindance-ops/omni_ruby'
chef_version     '>= 12.5.0'
supports         'redhat'
supports         'centos'
supports         'ubuntu'
supports         'debian'
depends 'apt'
depends 'build-essential'
