---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41
  
platforms:
  - name: windows2012r2
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      customize:
        memory: '2048'
        cpus: '2'
        vram: '32'
        clipboard: bidirectional
        draganddrop: bidirectional

suites:
- name: default
  run_list: ["recipe[summary_handlers_test]", "recipe[summary_handlers]"]
  attributes:
