---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
  - name: centos-7.1

  # - name: opentable/win-2008r2-standard-amd64-nocm # Not currently working
  #   os_type: windows
  #   shell_type: powershell
  #   transport: winrm
  
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    transport: winrm

suites:
  - name: default
    run_list:
      - recipe[filezilla::default]
    attributes:

  - name: server
    run_list:
      - recipe[filezilla::server]
    attributes:
    includes:
      - opentable/win-2012r2-standard-amd64-nocm
