---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 5
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: el7
    run_list:
      - recipe[fipsify]
    verifier:
      inspec_tests:
        - test/smoke/linux
    attributes:
