---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - 'recipe[apt::default]'
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-5.10
    attributes:
      cobbler:
        packages:
          - cobbler

suites:
  - name: default
    run_list:
      - 'recipe[cobbler::default]'
  - name: web
    run_list:
      - 'recipe[cobbler::web]'
    excludes:
      - centos-5.10
