---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: single
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 8001}]
        - ["private_network", {ip: "192.168.33.1"}]
    run_list:
      - recipe[single::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
  # - name: multiple
  #   driver_config:
  #     network:
  #       - ["forwarded_port", {guest: 8080, host: 8002}]
  #       - ["private_network", {ip: "192.168.33.2"}]
  #   run_list:
  #     - recipe[multiple::default]
  #   verifier:
  #     inspec_tests:
  #       - test/recipes
  #   attributes:
