require "rake"

task default: :test
task test: [:rubocop, :spec]

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new do |t|
  t.rspec_opts = \
    " --format progress" \
    " --format RspecJunitFormatter" \
    " --out test-reports/rspec.xml"
end

require "rubocop/rake_task"
require "rubocop/formatter/base_formatter"
require "rubocop/formatter/junit_formatter"
desc "Run RuboCop on the lib directory"
RuboCop::RakeTask.new(:rubocop) do |task|
  task.fail_on_error = false
  task.options << "--format"
  task.options << "files"
  task.options << "--format"
  task.options << "RuboCop::Formatter::JUnitFormatter"
  task.options << "--out"
  task.options << "test-reports/rubocop.xml"
end
