---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1
  - name: centos-7.2
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[dotnetcore::default]
    attributes:
