inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - metadata.rb
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    - Gemfile
    - '.kitchen/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 200
