name             'ultradns_client'
maintainer       'General Electric'
maintainer_email 'brent.walker@ge.com'
license          'All rights reserved'
description      'Installs/Configures ultradns_client'
long_description 'Installs/Configures ultradns_client'
version          '1.0.1'

supports 'ubuntu'
supports 'centos'
