---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    transport:
      name: winrm

suites:
  - name: server-community
    run_list:
      - recipe[minitest-handler]
      - recipe[sync-gateway::default]
    attributes: {}
