driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-16.04
- name: centos-6.8

suites:
- name: default
  run_list: ["recipe[xinetd]"]
  attributes: {}
- name: builtin_services
  run_list: ["recipe[xinetd::builtin_services]"]
  attributes: {}
