---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  require_chef_omnibus: 12.18.31

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[alfresco-utils::package-repositories]
      - recipe[alfresco-transformations::default]
      - recipe[alfresco-transformations::initialise_libreoffice]
      - recipe[alfresco-utils::node_json]
    attributes: {
      "transformations": {
        "libreoffice" : {
            "initialise": {
                "enabled" : true
              }
            }
          }
        }
    verifier:
      inspec_tests:
        - name: chef-alfresco-inspec-transformations
          git: https://github.com/Alfresco/chef-alfresco-inspec-transformations
          tag: v1.1
  - name: extras
    run_list:
      - recipe[alfresco-utils::package-repositories]
      - recipe[alfresco-transformations::default]
      - recipe[alfresco-utils::node_json]
    attributes: {
      "transformations": {
            "imagemagick": {
                "use_im_os_repo" : true
              }
            }
          }
    verifier:
      inspec_tests:
        - name: chef-alfresco-inspec-transformations
          git: https://github.com/Alfresco/chef-alfresco-inspec-transformations
          tag: v1.1
