---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero
  attributes:
    twindb_agent:
      registration_code: "0f6714f735a06a488ec9279f59d0a3f2"
    mysql:
      root_password: "root"

platforms:
  - name: centos-6.6
    attributes:
      mysql:
        socket: "/var/run/mysql-default/mysqld.sock"
  - name: centos-7.0
    attributes:
      mysql:
        socket: "/var/run/mysql-default/mysqld.sock"
  - name: debian-7.8
    attributes:
      mysql:
        socket: "/run/mysql-default/mysqld.sock"
  - name: debian-8.1
    attributes:
      mysql:
        socket: "/run/mysql-default/mysqld.sock"
  - name: ubuntu-12.04
    attributes:
      mysql:
        socket: "/run/mysql-default/mysqld.sock"
  - name: ubuntu-14.04
    attributes:
      mysql:
        socket: "/run/mysql-default/mysqld.sock"

suites:

  - name: server55-default
    run_list:
      - recipe[test-helper]
      - recipe[mysql_server_client_test]
      - recipe[mysql-test-schema::sakila]
      - recipe[rngd-tools]
      - recipe[twindb-agent]
    attributes:
      mysql:
       version: '5.5'

  - name: server56-default
    run_list:
      - recipe[test-helper]
      - recipe[mysql_server_client_test]
      - recipe[mysql-test-schema::sakila]
      - recipe[rngd-tools]
      - recipe[twindb-agent]
    excludes:
      - debian-7.8
      - debian-8.1
      - ubuntu-12.04
    attributes:
      mysql:
       version: '5.6'
