---
driver:
  name: ec2
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  aws_ssh_key_id: travis-ci-aws-frank
  security_group_ids: ["sg-2dc50845"]
  region: eu-central-1
  require_chef_omnibus: 12
  instance_type: t2.micro
  tags:
    Name: travis-ci-zabbix_lwrp

transport:
  ssh_key: '.travis/travis-ci-aws-frank.pem'
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-6bee0004
    transport:
      username: ubuntu
  - name: ubuntu-16.04
    driver:
      image_id: ami-f9e30f96
    transport:
      username: ubuntu
  - name: centos-73
    driver:
      image_id: ami-7cbc6e13

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/inspec


suites:
  - name: zabbix24-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix24_mysql]
    excludes:
      - ubuntu-16.04
    verifier:
      attributes:
        db: mysql

  - name: zabbix24-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix24_postgresql]
    excludes:
      - ubuntu-16.04
    verifier:
      attributes:
        db: postgresql

  - name: zabbix30-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix30_mysql]
    verifier:
      attributes:
        db: mysql

  - name: zabbix30-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix30_postgresql]
    verifier:
      attributes:
        db: postgresql

  - name: zabbix32-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_mysql]
    verifier:
      attributes:
        db: mysql

  - name: zabbix32-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_postgresql]
    verifier:
      attributes:
        db: postgresql
