---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
- name: centos-6.6
- name: win2012

suites:
- name: client
  run_list: ["recipe[opsview_client_test::test]"]
  attributes: { 'opsview' : { 'server_url' : 'uat.opsview.com' } }
