
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk=1.1.16-1

services:
  - docker

env:
  - INSTANCE=ubuntu
  - INSTANCE=centos

install: true

script: kitchen test ${INSTANCE}

after_failure: cat .kitchen/logs/*

matrix:
  include:
    - before_script: true
      script:
      - cookstyle -D
      - foodcritic --exclude test .
      env: UNIT_AND_LINT=1

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b234cf297a40_key -iv $encrypted_b234cf297a40_iv -in supermarket.pem.enc -out supermarket.pem -d

deploy:
  provider: chef-supermarket
  edge: true
  user_id: redguide
  client_key: supermarket.pem
  cookbook_category: Other
  skip_cleanup: true
  on:
    tags: true
    branch: master
