---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list: spigot::default
    attributes:
