language: generic

sudo: true

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

install: echo "skip bundle install"

services: docker

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install kitchen-docker

script:
  - ls
  - pwd
  - chef exec rake
