---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-9.3
  - name: ubuntu-16.04
  - name: centos-7.4
  - name: fedora-27
    run_list:
      - yum::dnf_yum_compat

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: cluster-client
    driver:
      network:
        - - private_network
          - ip: 192.168.120.201
    includes:
      - centos-7.4
    run_list:
      - recipe[cluster::client]
  - name: cluster-server
    driver:
      network:
        - - private_network
          - ip: 192.168.120.101
        - - forwarded_port
          - guest: 4646
            host: 4646
    includes:
      - centos-7.4
    run_list:
      - recipe[cluster::server]
      - recipe[cluster::jobs]
