---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: <%= !ENV['CACHE_COOKBOOKS'] %>

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: server_example
    run_list:
      - recipe[rancher-ng::test]
      - recipe[rancher-ng::server]
    attributes:
  - name: agent_example
    run_list:
      - recipe[rancher-ng::test]
      - recipe[rancher-ng::agent]
    attributes:
  - name: default
    run_list:
      - recipe[rancher-ng]
    attributes:
  - name: agent
    run_list:
      - recipe[test]
      - recipe[test::agent_example]
    attributes:
  - name: server
    run_list:
      - recipe[test]
      - recipe[test::server_example]
    attributes:
      rancher_ng: 
        agent: 
          auth_url: 'http://localhost:8080/SOMETOKEN'
