---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-9.2
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[redis-simple::default]
    attributes:
