---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  cookbooks_path: test/fixtures/cookbooks
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: 13.8.5

platforms:
  - name: centos-7.4

suites:
  - name: standalone
    run_list:
      - recipe[mongotest::test_standalone]

  - name: replset1
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        private_network:
          ip: "172.16.20.10"

  - name: replset2
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        private_network:
          ip: "172.16.20.11"

  - name: replset-hidden
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        private_network:
          ip: "172.16.20.12"

  - name: replset3
    run_list:
      - recipe[mongotest::test_replset_init]
    driver:
      network:
        private_network:
          ip: "172.16.20.13"

  - name: shard1
    run_list:
      - recipe[mongotest::test_shard]
    driver:
      network:
        private_network:
          ip: "172.16.20.21"

  - name: shard2
    run_list:
      - recipe[mongotest::test_shard]
    driver:
      network:
        private_network:
          ip: "172.16.20.22"

  - name: cfg1
    run_list:
      - recipe[mongotest::test_cfg]
    driver:
      network:
        private_network:
          ip: "172.16.20.23"

  - name: cfg2
    run_list:
      - recipe[mongotest::test_cfg]
    driver:
      network:
        private_network:
          ip: "172.16.20.24"

  - name: cfg3
    run_list:
      - recipe[mongotest::test_cfg_init]
    driver:
      network:
        private_network:
          ip: "172.16.20.25"

  - name: shard_set1
    run_list:
      - recipe[mongotest::test_shard_set]
    driver:
      network:
        private_network:
          ip: "172.16.20.26"

  - name: shard_set2
    run_list:
      - recipe[mongotest::test_shard_set]
    driver:
      network:
        private_network:
          ip: "172.16.20.27"

  - name: shard_set3
    run_list:
      - recipe[mongotest::test_shard_init]
    driver:
      network:
        private_network:
          ip: "172.16.20.28"

  - name: mongos
    run_list:
      - recipe[mongotest::test_mongos]
    driver:
      network:
        private_network:
          ip: "172.16.20.29"
