---
driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  environments_path: test/environments
  environment: kitchen

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[jolokia-jvm-agent::default]
    attributes:
      jolokia-jvm-agent:
        version: '1.3.2'
        dir: '/opt/jolokia'
