---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 6444}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 6445}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 6446}]

suites:
  - name: default
    run_list:
      - recipe[chromedriver_test::packages]
      - recipe[chromedriver_test::default]
    attributes:
