driver:
  name: digitalocean
  private_networking: false
  size: 2gb

transport:
  name: rsync

provisioner:
  attributes:
    apt:
      compile_time_update: true
  client_rb:
    formatters:
      # Keeps logs concise for parallelism.
      # Travis CI will also cancel job if logs get over 4MB.
    - :minimal
