name             'netdevops'
maintainer       'John Deatherage'
maintainer_email 'john@routeoflastresort.com'
license          'apache2'
description      'Installs NetDevOps environment'
long_description 'Installs NetDevOps environment'
version          '0.2.7'
source_url       'https://github.com/netdevops/netdevops-cookbook'
issues_url       'https://github.com/netdevops/netdevops-cookbook/issues'

provides 'netdevops::default'
recipe 'netdevops::default', 'install NetDevOps packages'
provides 'netdevops::desktop'
recipe 'netdevops::desktop', 'install NetDevOps desktop environment packages'
provides 'netdevops::opencontrail'
recipe 'netdevops::opencontrail', 'install NetDevOps OpenContrail API client packages'

depends 'ark', '~> 0.9'
depends 'apt', '~> 2.6'
depends 'build-essential', '~> 2.1.3'
depends 'chef-dk', '~> 3.0.0'
depends 'chruby', '~> 0.2.2'
depends 'docker', '~> 0.36'
depends 'golang', '~> 1.5'
depends 'pyenv', '~> 0.1.0'
depends 'python', '~> 1.4'
depends 'rbenv', '~> 1.7'
depends 'vagrant', '~> 0.2'
depends 'yum', '~> 3.5'
depends 'yum-epel', '~> 0.6.0'

# sticking with Ubuntu 14.04+ for now
# debian should work, but haven't tested
# supports 'debian', '>= 7.0'
supports 'ubuntu', '>= 14.04'
supports 'redhat', '>= 6.5'
supports 'centos', '>= 6.6'
