---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '13'

platforms:
- name: ubuntu-14.04
  driver_config:
    box: bento/ubuntu-14.04
    customize:
      memory: 512

- name: ubuntu-16.04
  driver_config:
    box: bento/ubuntu-16.04
    customize:
      memory: 512

- name: centos-6
  driver_config:
    box: bento/centos-6
    customize:
      memory: 512
  attributes:
    dw_test:
      init_platform: 'sysv'

- name: centos-7
  driver_config:
    box: bento/centos-7
    customize:
      memory: 512

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[dw_test]
  verifier:
    inspec_tests:
      - test/cookbooks/dw_test/test/integration/default
  attributes: {}
