---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: debian78
    driver:
      box: bento/debian-7.8
      box_url: bento/debian-7.8
  - name: centos511
    driver:
      box: bento/centos-5.11
      box_url: bento/centos-5.11
  - name: centos67
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
  - name: freebsd10
    driver:
      box: bento/freebsd-10.2
      box_url: bento/freebsd-10.2


suites:
  - name: default
    run_list:
      - recipe[linux-tweak::default]
    attributes:
  - name: bashoverride
    run_list:
      - recipe[linux-tweak::default]
    attributes:
      linux-tweak:
        PS1: 'export PS1="\[\033[38;5;0m\](\[$(tput sgr0)\]\[\033[38;5;15m\]\u\[$(tput sgr0)\]\[\033[38;5;0m\]@\[$(tput sgr0)\]\[\033[38;5;15m\]\h-\[$(tput sgr0)\]\[\033[38;5;0m\])(\[$(tput sgr0)\]\[\033[38;5;15m\]\t\[$(tput sgr0)\]\[\033[38;5;0m\])\[$(tput sgr0)\]\[\033[38;5;15m\]-\[$(tput sgr0)\]\[\033[38;5;0m\](\[$(tput sgr0)\]\[\033[38;5;12m\]\w\[$(tput sgr0)\]\[\033[38;5;0m\])\[$(tput sgr0)\]\[\033[38;5;15m\]\n\[$(tput sgr0)\]\[\033[38;5;0m\]>\[$(tput sgr0)\]"'
