rvm:
- 2.2
- 2.3

sudo: required

env:
- CHEF_VERSION="~> 12.0"

matrix:
  exclude:
  # Chef 12.9 requires Ruby >= 2.1
  - rvm: 2.0.0
    env: CHEF_VERSION="~> 12.0"

before_install:
- gem install bundler # Update bundler
- gem update --system # https://github.com/sickill/rainbow/issues/48

bundler_args: --jobs=3 --retry=3 --without='doc integration integration_docker integration_vagrant integration_cloud guard'

script: travis_retry bundle exec rake style unit
