---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[lita::default]
    attributes:
      lita:
        gem_primary_source: 'https://rubygems.org'
        name: fakebot
        version: '4.6'
        log_level: :info
        daemon_user: vagrant
        daemon_group: vagrant
        admin:
          - User1
          - User2
        init_style: init
        plugins:
          - google-images
          - pagerduty
          - coin: ':git => "git://github.com/jimmycuadra/lita-coin.git"'
        plugin_config:
          google_images:
            safe_search: "off"
          fake_plugin:
            array:
              - key1
              - key2
            array_of_hash:
              - key1: value1
              - key2: value2
            hash_of_hash:
              top1:
                key1: value1
                key2: value2
              top2:
                key1: value1
                key2: value2
            hash_of_array:
              top1:
                - key1
                - key2
              top2:
                - key1
                - key2
            hash:
              key1: value1
              key2: value2
          fake_plugin2:
            array_string: "['item1', 'item2', 'item3']"
            hash_string: "{ 'key1' => 'value1', 'key2' => 'value2' }"
            fixnum_string: "100"
            float_string: "0.1"
            true_string: "true"
            false_string: "false"
            symbol_string: ":symbol"
        gems:
          - pagerduty-sdk: ':git => "https://github.com/kryptek/pagerduty-sdk.git"'
  - name: runit
    run_list:
      - recipe[lita::default]
    attributes:
      lita:
        name: fakebot
        version: '4.6'
        log_level: :info
        daemon_user: vagrant
        daemon_group: vagrant
        install_dir: /home/vagrant
        log_dir: /home/vagrant/logs
        run_dir: /home/vagrant/run
        runit:
          env:
            HOME: /tmp
            PATH: /opt/chef/embedded/bin:/opt/chef/embedded/bin/gem
            LITA: Just a fake value for testing
        plugins:
          - google-images
          - pagerduty
          - coin: ':git => "git://github.com/jimmycuadra/lita-coin.git"'
        gems:
          - pagerduty-sdk: ':git => "https://github.com/kryptek/pagerduty-sdk.git"'
