---
driver:
  name: vagrant
  gui: true
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  log_level: auto
  client_rb:
      add_formatter: doc

platforms:
  - name: debian8
    driver_config:
      box: debian/jessie64
    provisioner:
      require_chef_omnibus: 12.20.3
  
  - name: debian9
    driver_config:
      box: debian/stretch64
    provisioner:
      require_chef_omnibus: 13.6.4

  - name: ubuntu1604
    driver_config:
      box: ubuntu/xenial64
    provisioner:
      require_chef_omnibus: 13.6.4
    
  - name: ubuntu1710
    driver_config:
      box: ubuntu/artful64
    provisioner:
      require_chef_omnibus: 13.6.4

  - name: centos7
    driver_config:
      box: centos/7
    provisioner:
      require_chef_omnibus: 12.20.3

# The following platforms are private boxes and are not available from the vagrant box repository
# Follow instructions provided in TESTING.md to create a box

# To a use a private box:
# 1. Create a box. To do so, follow the instructions in TESTING.md
# 2. Once you've added the vagrant box, modify this file to use it
# 3. In the 'suites' section of this file, list your box name(s) under 'includes' for the corresponding platform
# 4. Confirm your box shows up when running `vagrant box list` and `kitchen list` when in this cookbook directory

  - name: osx1012
    driver:
      box: osx1012
      username: <%= ENV['BOX_USERNAME'] %>
    provisioner:
      require_chef_omnibus: 13.6.4

  - name: windows10
    driver_config:
      guest: windows
      communicator: 'winrm'
      box: win10x64-enterprise
    provisioner:
      require_chef_omnibus: 13.6.4

  - name: windows-2012-r2
    driver_config:
      guest: windows
      communicator: 'winrm'
      box: windows-2012-r2
    provisioner:
      require_chef_omnibus: 13.0.118

suites:
  - name: windows-basic
    run_list:
      - recipe[windows-basic::default]
    includes:
      - windows10
      - windows-2012-r2
    attributes:
        vsts_agent_test:
            username: <%= ENV['BOX_USERNAME'] %>
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>

  - name: linux-basic
    run_list:
      - recipe[linux-basic::default]
    includes:
      - debian8
      - debian9
      - ubuntu1604
      - ubuntu1710
      - centos7

    attributes:
        vsts_agent_test:
            username: <%= ENV['BOX_USERNAME'] %>
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>

  - name: osx-basic
    run_list:
      - recipe[osx-basic::default]
    includes:
      - osx1012

    attributes:
        vsts_agent_test:
            username: <%= ENV['BOX_USERNAME'] %>
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>

