sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=client-centos-6
  - INSTANCE=client-centos-7
  - INSTANCE=client-debian-7
  - INSTANCE=client-debian-8
  - INSTANCE=client-fedora-25
  - INSTANCE=client-opensuse-leap
  - INSTANCE=client-ubuntu-1404
  - INSTANCE=client-ubuntu-1604
  - INSTANCE=yum-pgdg-client-centos-6
  - INSTANCE=yum-pgdg-client-centos-7
  - INSTANCE=yum-pgdg-client-fedora-25
  - INSTANCE=apt-pgdg-client-debian-7
  - INSTANCE=apt-pgdg-client-debian-8
  - INSTANCE=apt-pgdg-client-ubuntu-1404
  - INSTANCE=apt-pgdg-client-ubuntu-1604
  - INSTANCE=yum-pgdg-client-ruby-centos-6
  - INSTANCE=yum-pgdg-client-ruby-centos-7
  - INSTANCE=yum-pgdg-client-ruby-fedora-25
  - INSTANCE=apt-pgdg-client-ruby-debian-7
  - INSTANCE=apt-pgdg-client-ruby-debian-8
  - INSTANCE=apt-pgdg-client-ruby-ubuntu-1404
  - INSTANCE=apt-pgdg-client-ruby-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1
