name             'diskanalyser'
maintainer       'Livelink Technology LTD'
maintainer_email 'infra@livelinktechnology.net'
license          'All rights reserved'
description      'Installs/Configures diskanalyser'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.4'
chef_version '> 12'
source_url 'https://github.com/livelink/diskanalyser'
issues_url 'https://github.com/livelink/diskanalyser/issues'
supports 'debian'
supports 'centos'
depends 'ohai'
depends 'apt'
