---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[air]
    attributes:
      air:
        path: http://download.macromedia.com/pub/developer/air/sample_apps/Bee.air
        location: C:\air\sample_apps
        update_disabled: true
