name 'test-is'
maintainer 'Make.org'
maintainer_email 'sre@make.org'
license 'Apache-2.0'
description 'Test iptables-services on linux nodes'
long_description 'Test iptables-services on linux nodes'
source_url 'https://gitlab.com/chef-platform/iptables-services'
issues_url 'https://gitlab.com/chef-platform/iptables-services/issues'
version '1.0.0'
