---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 58080, host: 58080}]
    - ["private_network", {ip: "192.168.2.110"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

attributes:
  chef_client:
    config:
      log_level: ":debug"

suites:
  - name: default
    run_list:
      - recipe[opencart::create_ubuntu_env_for_test]
      - recipe[opencart::create_database]
      - recipe[opencart::default]
      - recipe[opencart::create_tables]
      - recipe[opencart::apache2_restart]
      - recipe[opencart::test]
    attributes:
      opencart:
         git_url: https://github.com/opencart/opencart.git
