---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.9
  - name: centos-7.3

verifier:
    name: inspec

suites:
  - name: default
    run_list:
      - recipe[yum-plugin-versionlock::default]
      - recipe[test::lwrp]
