---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/roles

verifier:
  name: inspec

platforms:
- name: centos-6.9
- name: centos-7.3
- name: debian-7.11
- name: debian-8.7
- name: fedora-21
- name: fedora-22
- name: fedora-23
- name: fedora-24
- name: fedora-25
- name: ubuntu-14.04
- name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
  - name: version-pin
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        version: 2016.3.0-1.el7
    includes:
      - centos-7
      - centos-7.3
  - name: salt-api
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        master:
          api:
            enable: true
