# Main pgpool.conf values
default['pg']['config']['pgpool']['listen_addresses'] = 'localhost'
default['pg']['config']['pgpool']['port'] = 9999
default['pg']['config']['pgpool']['socket_dir'] = '/tmp'
default['pg']['config']['pgpool']['listen_backlog_multiplier'] = 2
default['pg']['config']['pgpool']['serialize_accept'] = false
default['pg']['config']['pgpool']['pcp_listen_addresses'] = '*'
default['pg']['config']['pgpool']['pcp_port'] = 9898
default['pg']['config']['pgpool']['pcp_socket_dir'] = '/tmp'
default['pg']['config']['pgpool']['backend_hostname0'] = 'localhost'
default['pg']['config']['pgpool']['backend_port0'] = 5432
default['pg']['config']['pgpool']['backend_weight0'] = 1
default['pg']['config']['pgpool']['backend_data_directory0'] = ''
default['pg']['config']['pgpool']['backend_flag0'] = 'ALLOW_TO_FAILOVER'
default['pg']['config']['pgpool']['enable_pool_hba'] = false
default['pg']['config']['pgpool']['authentication_timeout'] = 60
default['pg']['config']['pgpool']['ssl'] = false
default['pg']['config']['pgpool']['num_init_children'] = 32
default['pg']['config']['pgpool']['max_pool'] = 4
default['pg']['config']['pgpool']['child_life_time'] = 300
default['pg']['config']['pgpool']['child_max_connections'] = 0
default['pg']['config']['pgpool']['connection_life_time'] = 0
default['pg']['config']['pgpool']['client_idle_limit'] = 0
default['pg']['config']['pgpool']['log_destination'] = 'stderr'
default['pg']['config']['pgpool']['log_line_prefix'] = '%t: pid %p: '
default['pg']['config']['pgpool']['log_connections'] = false
default['pg']['config']['pgpool']['log_hostname'] = false
default['pg']['config']['pgpool']['log_statement'] = false
default['pg']['config']['pgpool']['log_per_node_statement'] = false
default['pg']['config']['pgpool']['log_standby_delay'] = 'none'
default['pg']['config']['pgpool']['syslog_facility'] = 'LOCAL0'
default['pg']['config']['pgpool']['syslog_ident'] = 'pgpool'
default['pg']['config']['pgpool']['debug_level'] = 0
default['pg']['config']['pgpool']['connection_cache'] = true
default['pg']['config']['pgpool']['reset_query_list'] = 'ABORT; DISCARD ALL'
default['pg']['config']['pgpool']['replication_mode'] = false
default['pg']['config']['pgpool']['insert_lock'] = true
default['pg']['config']['pgpool']['lobj_lock_table'] = ''
default['pg']['config']['pgpool']['replication_stop_on_mismatch'] = false
default['pg']['config']['pgpool']['failover_if_affected_tuples_mismatch'] = false # rubocop:disable Metrics/LineLength
default['pg']['config']['pgpool']['load_balance_mode'] = false
default['pg']['config']['pgpool']['ignore_leading_white_space'] = true
default['pg']['config']['pgpool']['white_function_list'] = ''
default['pg']['config']['pgpool']['black_function_list'] = 'nextval,setval,nextval,setval' # rubocop:disable Metrics/LineLength
default['pg']['config']['pgpool']['database_redirect_preference_list'] = ''
default['pg']['config']['pgpool']['app_name_redirect_preference_list'] = ''
default['pg']['config']['pgpool']['allow_sql_comments'] = false
default['pg']['config']['pgpool']['master_slave_mode'] = false
default['pg']['config']['pgpool']['master_slave_sub_mode'] = 'slony'
default['pg']['config']['pgpool']['sr_check_period'] = 0
default['pg']['config']['pgpool']['sr_check_user'] = 'nobody'
default['pg']['config']['pgpool']['sr_check_password'] = ''
default['pg']['config']['pgpool']['sr_check_database'] = 'postgres'
default['pg']['config']['pgpool']['delay_threshold'] = 0
default['pg']['config']['pgpool']['follow_master_command'] = ''
default['pg']['config']['pgpool']['health_check_period'] = 0
default['pg']['config']['pgpool']['health_check_timeout'] = 20
default['pg']['config']['pgpool']['health_check_user'] = 'nobody'
default['pg']['config']['pgpool']['health_check_password'] = ''
default['pg']['config']['pgpool']['health_check_database'] = ''
default['pg']['config']['pgpool']['health_check_max_retries'] = 0
default['pg']['config']['pgpool']['health_check_retry_delay'] = 1
default['pg']['config']['pgpool']['failover_command'] = ''
default['pg']['config']['pgpool']['failback_command'] = ''
default['pg']['config']['pgpool']['fail_over_on_backend_error'] = true
default['pg']['config']['pgpool']['search_primary_node_timeout'] = 10
default['pg']['config']['pgpool']['recovery_user'] = 'nobody'
default['pg']['config']['pgpool']['recovery_password'] = ''
default['pg']['config']['pgpool']['recovery_1st_stage_command'] = ''
default['pg']['config']['pgpool']['recovery_2nd_stage_command'] = ''
default['pg']['config']['pgpool']['recovery_timeout'] = 90
default['pg']['config']['pgpool']['client_idle_limit_in_recovery'] = 0
default['pg']['config']['pgpool']['use_watchdog'] = false
default['pg']['config']['pgpool']['trusted_servers'] = ''
default['pg']['config']['pgpool']['ping_path'] = '/bin'
default['pg']['config']['pgpool']['wd_hostname'] = ''
default['pg']['config']['pgpool']['wd_port'] = 9000
default['pg']['config']['pgpool']['wd_priority'] = 1
default['pg']['config']['pgpool']['wd_authkey'] = ''
default['pg']['config']['pgpool']['wd_ipc_socket_dir'] = '/tmp'
default['pg']['config']['pgpool']['delegate_IP'] = ''
default['pg']['config']['pgpool']['if_cmd_path'] = '/sbin'
default['pg']['config']['pgpool']['if_up_cmd'] = "ip addr add $_IP_$/24 dev #{node['network']['default_interface']} label #{node['network']['default_interface']}:0" # rubocop:disable Metrics/LineLength
default['pg']['config']['pgpool']['if_down_cmd'] = "ip addr del $_IP_$/24 dev #{node['network']['default_interface']}" # rubocop:disable Metrics/LineLength
default['pg']['config']['pgpool']['arping_path'] = '/usr/sbin'
default['pg']['config']['pgpool']['arping_cmd'] = 'arping -U $_IP_$ -w 1'
default['pg']['config']['pgpool']['clear_memqcache_on_escalation'] = true
default['pg']['config']['pgpool']['wd_escalation_command'] = ''
default['pg']['config']['pgpool']['wd_de_escalation_command'] = ''
default['pg']['config']['pgpool']['wd_monitoring_interfaces_list'] = ''
default['pg']['config']['pgpool']['wd_lifecheck_method'] = 'heartbeat'
default['pg']['config']['pgpool']['wd_interval'] = 10
default['pg']['config']['pgpool']['wd_heartbeat_port'] = 9694
default['pg']['config']['pgpool']['wd_heartbeat_keepalive'] = 2
default['pg']['config']['pgpool']['wd_heartbeat_deadtime'] = 30
default['pg']['config']['pgpool']['heartbeat_destination0'] = 'host0_ip1'
default['pg']['config']['pgpool']['heartbeat_destination_port0'] = 9694
default['pg']['config']['pgpool']['heartbeat_device0'] = ''
default['pg']['config']['pgpool']['wd_life_point'] = 3
default['pg']['config']['pgpool']['wd_lifecheck_query'] = 'SELECT 1'
default['pg']['config']['pgpool']['wd_lifecheck_dbname'] = 'template1'
default['pg']['config']['pgpool']['wd_lifecheck_user'] = 'nobody'
default['pg']['config']['pgpool']['wd_lifecheck_password'] = ''
default['pg']['config']['pgpool']['relcache_expire'] = 0
default['pg']['config']['pgpool']['relcache_size'] = 256
default['pg']['config']['pgpool']['check_temp_table'] = true
default['pg']['config']['pgpool']['check_unlogged_table'] = true
default['pg']['config']['pgpool']['memory_cache_enabled'] = false
default['pg']['config']['pgpool']['memqcache_method'] = 'shmem'
default['pg']['config']['pgpool']['memqcache_memcached_host'] = 'localhost'
default['pg']['config']['pgpool']['memqcache_memcached_port'] = 11_211
default['pg']['config']['pgpool']['memqcache_total_size'] = 67_108_864
default['pg']['config']['pgpool']['memqcache_max_num_cache'] = 1_000_000
default['pg']['config']['pgpool']['memqcache_expire'] = 0
default['pg']['config']['pgpool']['memqcache_auto_cache_invalidation'] = true
default['pg']['config']['pgpool']['memqcache_maxcache'] = 409_600
default['pg']['config']['pgpool']['memqcache_cache_block_size'] = 1_048_576
default['pg']['config']['pgpool']['memqcache_oiddir'] = '/var/log/pgpool/oiddir'
default['pg']['config']['pgpool']['white_memqcache_table_list'] = ''
default['pg']['config']['pgpool']['black_memqcache_table_list'] = ''

# pool_hba default config
default['pg']['config']['pool_hba']['md5'] = {
  enabled: true,
  type: 'host',
  database: 'all',
  user: 'all',
  address: '0.0.0.0/0',
  method: 'md5'
}
