source 'https://rubygems.org'

gem 'berkshelf', '~> 3.0.0.beta3'

group :integration do
  gem 'test-kitchen', '~> 1.0.0.beta.1'
  gem 'kitchen-vagrant', '~> 0.11.3'
end

group :test do
  gem 'foodcritic', '~> 3.0.3'
  gem 'rubocop',    '~> 0.15.0'
end

group :development do
  gem 'chef'
end
