---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    heartbeat:
      config:
        output.elasticsearch:
            hosts: ["127.0.0.1:9200"]
        heartbeat.monitors:
          - type: icmp
            schedule: '*/5 * * * * * *'
            hosts: ['127.0.0.1']

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.8
    run_list:
    - recipe[yum]
  - name: centos-7.2
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[elastic-heartbeat::default]
  - name: version_6
    run_list:
      - recipe[elastic-heartbeat::default]
    attributes:
      heartbeat:
        version: '6.2.3'
