AllCops:
  Exclude:
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    - Gemfile
    - '.kitchen/*'
    - 'vendor/*'
AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 75
BracesAroundHashParameters:
  Enabled: true
CyclomaticComplexity:
  Enabled: false
GuardClause:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 50
ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
AbcSize:
  Enabled: false
