rpm7:
  dockerfile: dockerfiles/Dockerfile.centos-7
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: el7
  command: make rpm
rpm6:
  dockerfile: dockerfiles/Dockerfile.centos-6
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: el6
  command: make rpm
rpm5:
  dockerfile: dockerfiles/Dockerfile.centos-5
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: el5
  command: make rpm5

deb16:
  dockerfile: dockerfiles/Dockerfile.ubuntu-16
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: xenial
  command: make deb
deb14:
  dockerfile: dockerfiles/Dockerfile.ubuntu-14
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: trusty
  command: make deb
deb12:
  dockerfile: dockerfiles/Dockerfile.ubuntu-12
  build: .
  volumes:
    - .:/octopass
  environment:
    DIST: precise
  command: make deb12
