---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.15.19

verifier:
  name: inspec

platforms:
  - name: windows2012r2
    driver_config:
      box: windows2012r2
    transport: 
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[sbp_mremoteng::default]
    attributes:
      mremoteng:
        shared_config_dir: 'C:\MyConfigDir'
