---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-6
- name: centos-7
  driver_config:
    privileged: true
    run_command: /sbin/init
- name: debian-7
  run_list: recipe[apt]
- name: debian-8
  run_list: recipe[apt]
- name: oraclelinux-6
  driver_config:
    platform: rhel
- name: oraclelinux-7
  driver_config:
    platform: rhel
    privileged: true
    run_command: /sbin/init
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]
  driver_config:
    privileged: true
    run_command: /sbin/init
- name: ubuntu-16.10
  run_list: recipe[apt]
  driver_config:
    privileged: true
    run_command: /sbin/init
- name: fedora-25
  driver_config:
    privileged: true
    run_command: /sbin/init
