---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  client_rb:
    treat_deprecation_warnings_as_errors: true

platforms:
- name: centos-5.11
- name: centos-6.8
- name: centos-7.3
- name: debian-7.11
  run_list: recipe[apt]
- name: debian-8.6
  run_list: recipe[apt]
- name: fedora-23
- name: fedora-24
- name: fedora-25
- name: opensuse-13.2
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]
- name: ubuntu-16.10
  run_list: recipe[apt]

suites:
- name: default
  run_list: recipe[onddo-spamassassin_test]
