AllCops:
  Exclude:
  - .kitchen
  Include:
  - files/*/*.rb
  - '**/*.rb.erb'
FormatParameterMismatch:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - test/unit/**/*_spec.rb
  - test/integration/**/*_spec.rb
