# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'files/default/vendor/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 140

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 20

Style/MixinUsage:
  Exclude:
    - 'spec/**/dir_spec.rb'
