---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: centos-7.1
  - name: fedora-21
  - name: ubuntu-14.10

suites:
  - name: create
    run_list:
      - recipe[firewalldconfig_test::create]
    attributes:

  - name: merge-prune-filter
    run_list:
      - recipe[firewalldconfig_test::merge-prune-filter]
    attributes:
