Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 10
#
# we like our neatly-aligned code too much
#
SingleSpaceBeforeFirstArg:
  Enabled: false
#
# Rubocop was throwing suprious "snake_case" errors. This fixes that.
#
Style/FileName:
  Enabled: false
