---
driver:
  name: vagrant
  customize:
    memory: 1024

verifier:
  root_path: '/tmp/verifier'
  sudo: true

provisioner:
  name: chef_zero
  log_level: info
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-7
    driver:
      box: centos/7 # virtualbox, vmware, parallels
      image: centos-7-0-x64 # digitalocean

  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-14.04
      image: ubuntu-14-04-x64
    attributes:
      nginx:
        install_method: source
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-16.04
      image: ubuntu-16-04-x64
    attributes:
      nginx:
        install_method: source

suites:
- name: http
  run_list:
    - recipe[acme_server]
    - recipe[acme_client::http]
  attributes:
    boulder:
      revision: 2d33a9900cafe82993744fe73bd341fe47df2171
    acme:
      endpoint: http://127.0.0.1:4000
      contact:
      - mailto:admin@example.com
