---
driver_plugin: vagrant
driver_config:

platforms:
- name: chef10-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true

- name: chef10-ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: true

- name: chef10-centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true

- name: chef10-centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: true

suites:
- name: zenoss_client
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss_client_test::client_lwrp]
  attributes:
    zenoss:
      client:
        server: <%= ENV['ZENOSS_CLIENT_SERVER'] || '127.0.0.1' %>
        server_port: <%= ENV['ZENOSS_CLIENT_SERVER_PORT'] || '8080' %>
        test:
          run_lwrp_tests: true
          api_user: <%= ENV['ZENOSS_CLIENT_TEST_API_USER'] || 'admin' %>
          api_password: <%= ENV['ZENOSS_CLIENT_TEST_API_PASSWORD'] || 'zenoss' %>
          
        
