name 'corosync'
maintainer 'Petr Belyaev'
maintainer_email 'upcfrost@gmail.com'
license 'GPLv3.0'
description 'Installs/Configures Corosync'
long_description 'Installs/Configures Corosync'
version '0.1.1'
source_url 'https://github.com/upcFrost/chef_corosync_cookbook'
issues_url 'https://github.com/upcFrost/chef_corosync_cookbook/issues'

depends 'hostsfile'
depends 'poise-service'
depends 'yum'
depends 'apt'
depends 'zypper'

supports 'redhat', '>= 6.0'
supports 'centos', '>= 6.0'
supports 'ubuntu', '>= 14.04'
supports 'debian', '>= 8.0'
supports 'fedora'
supports 'suse'
