---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-7.0

suites:
  - name: mysql51
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[percona-tools::default]
    includes: [
      'centos-6.4',
      'centos-6.5'
    ]
    attributes:
      mysql:
        version: "5.1"
        root_password: "root"
        socket: "/var/run/mysql-default/mysqld.sock"
      percona_tools:
        ro_user: "ptro"
        rw_user: "ptrw"

  - name: mysql55
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[percona-tools::default]
    includes: [
      'centos-6.4',
      'centos-6.5',
      'centos-7.0'
    ]
    attributes:
      mysql:
        version: "5.5"
        root_password: "root"
        socket: "/var/run/mysql-default/mysqld.sock"
      percona_tools:
        ro_user: "ptro"
        rw_user: "ptrw"

  - name: mysql56
    run_list:
      - recipe[mysql_server_client_test::default]
      - recipe[percona-tools::default]
    includes: [
      'centos-6.4',
      'centos-6.5',
      'centos-7.0'
    ]
    attributes:
      mysql:
        version: "5.6"
        root_password: "root"
        socket: "/var/run/mysql-default/mysqld.sock"
      percona_tools:
        ro_user: "ptro"
        rw_user: "ptrw"