sudo: required
dist: trusty
cache: bundler
language: ruby
rvm:
  - "2.4.1"

env:
  matrix:
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=disable-ubuntu-1604
    - INSTANCE=remove-ubuntu-1604

bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"

services:
  - docker

script:
- "KITCHEN_LOCAL_YAML=.kitchen.dokken.yml bundle exec kitchen verify ${INSTANCE}"