---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.8

suites:
  - name: default
    require_chef_omnibus: 12.14.60
    run_list:
      - recipe[telegraf-ng::default]
    attributes:
      telegraf:
        version: 1.0.0
