sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk
services:
- docker
env:
- INSTANCE=default-ubuntu-1604
- INSTANCE=default-centos-7
install: true
before_script:
- chef gem install kitchen-dokken
script: kitchen test ${INSTANCE}
matrix:
  include:
  - before_script: true
    script:
    - cookstyle -D
    - foodcritic --exclude test .
    env: UNIT_AND_LINT=1
before_deploy:
- openssl aes-256-cbc -K $encrypted_6b0f22b9ebc1_key -iv $encrypted_6b0f22b9ebc1_iv
  -in supermarket.pem.enc -out supermarket.pem -d
deploy:
  skip_cleanup: true
  provider: chef-supermarket
  user_id: redguide
  client_key: supermarket.pem
  cookbook_category: Other
  on:
    tags: true
    branch: master
