---
driver:
  name: vagrant
  network: 
    - ["forwarded_port", {guest: 3389, host: 33389}] 

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: win2012r2

suites:
  - name: default
    run_list:
      - recipe[windows_schannel::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
