sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-6
  - INSTANCE=default-amazonlinux
  - INSTANCE=default-debian-9
  - INSTANCE=default-debian-8
  - INSTANCE=amazon-time-amazonlinux

install: echo "skip bundle install"

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
  - /opt/chefdk/embedded/bin/chef gem install rubocop
  - /opt/chefdk/embedded/bin/chef gem install fauxhai -v 5.6.0
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
