---
driver:
  ssh_key: <%= ENV['SSH_AGENT_PID'].nil? ? ENV['SSH_KEY_PATH'] : nil %>

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
<% unless ENV['DIGITALOCEAN_ACCESS_TOKEN'].empty? %>
- name: centos-5-8-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-6-5-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-6-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-8-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: ubuntu-15-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
<% end %>

- name: amazon-2014.09.2
  driver:
    name: ec2
    image_id: ami-8e682ce6
    instance_type: t1.micro
  transport:
    username: ec2-user

- name: amazon-2015.03.1
  driver:
    name: ec2
    image_id: ami-0f4cfd64
    instance_type: t1.micro
  transport:
    username: ec2-user

- name: amazon-2015.09.0
  driver:
    name: ec2
    image_id: ami-cf1066aa
    instance_type: t1.micro
  transport:
    username: ec2-user
