rvm:
- 2.0.0
- 2.1
- 2.2

sudo: required

services: docker

env:
  matrix:
# CHEF_VERSION is only for unit tests, no for test-kitchen:
  - TESTS="style unit" CHEF_VERSION="~> 11.0"
  - TESTS="style unit" CHEF_VERSION="~> 12.0"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[mysql-centos-6,verify]"
  - TESTS="integration[mysql-debian-7,verify]"
  - TESTS="integration[mysql-debian-8,verify]"
  - TESTS="integration[mysql-scientific-66,verify]"
  - TESTS="integration[postgresql-debian-7,verify]"
  - TESTS="integration[postgresql-debian-8,verify]"
  - TESTS="integration[postgresql-ubuntu-1204,verify]"
  - TESTS="integration[postgresql-ubuntu-1404,verify]"
  - TESTS="integration[sqlite-centos-6,verify]"
  - TESTS="integration[sqlite-debian-7,verify]"
  - TESTS="integration[sqlite-debian-8,verify]"
  - TESTS="integration[sqlite-ubuntu-1204,verify]"
  - TESTS="integration[sqlite-ubuntu-1404,verify]"
  - TESTS="integration[sqlite-ubuntu-1504,verify]"
  - TESTS="integration[sqlite-scientific-66,verify]"
  - TESTS="integration[nginx-debian-7,verify]"
  - TESTS="integration[nginx-debian-8,verify]"

matrix:
  exclude:
# Chef 11 cannot resolve dependencies in Ruby 2.2 (mixlib-shellout):
  - rvm: 2.2
    env: TESTS="style unit" CHEF_VERSION="~> 11.0"
# Disable integration tests in old Ruby versions:
  - rvm: 2.0.0
    env: TESTS="integration[mysql-centos-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[mysql-centos-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[mysql-debian-7,verify]"
  - rvm: 2.1
    env: TESTS="integration[mysql-debian-7,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[mysql-debian-8,verify]"
  - rvm: 2.1
    env: TESTS="integration[mysql-debian-8,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[mysql-scientific-66,verify]"
  - rvm: 2.1
    env: TESTS="integration[mysql-scientific-66,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[postgresql-debian-7,verify]"
  - rvm: 2.1
    env: TESTS="integration[postgresql-debian-7,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[postgresql-debian-8,verify]"
  - rvm: 2.1
    env: TESTS="integration[postgresql-debian-8,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[postgresql-ubuntu-1204,verify]"
  - rvm: 2.1
    env: TESTS="integration[postgresql-ubuntu-1204,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[postgresql-ubuntu-1404,verify]"
  - rvm: 2.1
    env: TESTS="integration[postgresql-ubuntu-1404,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-centos-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-centos-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-debian-7,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-debian-7,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-debian-8,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-debian-8,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-ubuntu-1204,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-ubuntu-1204,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-ubuntu-1404,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-ubuntu-1404,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-ubuntu-1504,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-ubuntu-1504,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[sqlite-scientific-66,verify]"
  - rvm: 2.1
    env: TESTS="integration[sqlite-scientific-66,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[nginx-debian-7,verify]"
  - rvm: 2.1
    env: TESTS="integration[nginx-debian-7,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[nginx-debian-8,verify]"
  - rvm: 2.1
    env: TESTS="integration[nginx-debian-8,verify]"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.8.0

install: chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake $TESTS
