---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04-chef-12.2.1
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      require_chef_omnibus: 12.2.1
  - name: ubuntu-14.04-chef-12.3.0
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      require_chef_omnibus: 12.3.0
  - name: ubuntu-14.04-chef-12.4.1
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      require_chef_omnibus: 12.4.1
  - name: ubuntu-14.04-chef-12.5.1
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      require_chef_omnibus: 12.5.1

suites:
  - name: concat_test
    run_list:
      - recipe[concat_test::test_create]
      - recipe[concat_test::test_redo]
      - recipe[concat_test::test_delete]
      - recipe[concat_test::test_cookbookfile]
