name 'concat'
maintainer 'Edmund Rhudy'
maintainer_email 'erhudy@gmail.com'
license 'apache2'
description 'Builds files out of smaller concatenated fragments'
long_description IO.read(::File.join(::File.dirname(__FILE__), 'README.md'))
version '0.3.3'
source_url 'https://github.com/erhudy/chef-concat'
issues_url 'https://github.com/erhudy/chef-concat/issues'
supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
supports 'mac_os_x'
