---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-15.04
- name: debian-7.8
- name: debian-8.1
- name: centos-6.7
- name: fedora-20
- name: fedora-21

suites:
- name: default
  run_list:
    - recipe[filesystem_resize_test::default]
  attributes:
