AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Metrics/AbcSize:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ModuleLength:
  Enabled: false
SignalException:
  Enabled: false
TrailingCommaInLiteral:
  Enabled: false
TrailingCommaInArguments:
  Enabled: false
WordArray:
  Enabled: false
